### ISSUE TITLE
Скомпилированный qlua.exe - ничего не выполняет.

### ISSUE THREAD

**Issue by SergMarkof** [swerg/qlua-exe#5]
Скомпилированный qlua.exe - ничего не выполняет.
То есть даже консоль не появляется. Ничего видимого не происходит.

Сам файл  qlua.exe - помещен в папку с info.exe.

**Comment by swerg** [comment]
Надо запускать в консоли. И увидеть help.

```
err: File is required as argument
Usage:
   qlua.exe <filename.lua> {<arg1> <arg2> ...}
```

"Интерактивный режим" не поддерживается, не видится такой надобности.

**Comment by swerg** [comment]
err: File is required as argument
Usage:
   qlua.exe <filename.lua> {<arg1> <arg2> ...}
